name: Build Asteroids Game

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame pyinstaller
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --collect-all pygame --add-data "sounds:sounds" --name asteroids-game main.py
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: asteroids-game-${{ matrix.os }}
        path: dist/